evaluation:
  num_episodes: 15
  max_steps_per_episode: 20
  timeout_seconds: 30

models:
  openai:
    model: "gpt-4-turbo"
    temperature: 0.1
    max_tokens: 150
  anthropic:
    model: "claude-3-sonnet-20240229"
    temperature: 0.1
    max_tokens: 150

prompting:
  max_history_steps: 5
  include_reasoning: true
  retry_on_invalid: true
  max_retries: 3 